name: Manual Mod Release

on:
  workflow_dispatch:  # 手动触发

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17  # 可根据需要改为 17 等

      - name: Read mod version from gradle.properties
        id: get_version
        run: |
          version=$(grep "^mod_version\s*=" gradle.properties | cut -d'=' -f2 | tr -d ' ')
          echo "mod_version=$version"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Build mod
        run: ./gradlew build

      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v${{ steps.get_version.outputs.version }}
          git push origin v${{ steps.get_version.outputs.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: v${{ steps.get_version.outputs.version }}
          files: build/libs/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
